language: python

python:
  - "2.7"

before_install:
  - sudo apt-get update
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - sudo apt-get install wine
  - wget http://www.python.org/ftp/python/2.7.6/python-2.7.6.msi
  - DISPLAY=:99.0 wine msiexec /i python-2.7.6.msi /qn

script:
  - echo "Ok"
    #  - sh scripts/run_tests_wine.sh
