language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

env:
  - CFFI=true BITS=32
  - CFFI=false BITS=32
  - CFFI=true BITS=64
  - CFFI=false BITS=64

# The pywin32-219 installers for python 2.6 and 3.2 64bit are missing a files.
matrix:
  exclude:
    - python: "2.6"
      env: CFFI=false BITS=64
    - python: "3.2"
      env: CFFI=false BITS=64
    - python: "2.6"
      env: CFFI=true BITS=64
    - python: "3.2"
      env: CFFI=true BITS=64

before_install:
  - sudo add-apt-repository ppa:ubuntu-wine/ppa -y
  - sudo apt-get update
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - sudo apt-get install -y --force-yes wine
  - pip install coveralls
  - sh scripts/setup_tests_wine.sh

script:
  - sh scripts/run_tests_wine.sh

after_success:
  coveralls
