language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

env:
  - BITS=32
  - BITS=64

# The pywin32-219 installers for python 2.6 64bit are missing files.
# 64-bit for 2.7, 3.3 and 3.4 are testing with appveyor.
matrix:
  exclude:
    - python: "2.6"
      env: BITS=64
    - python: "2.7"
      env: BITS=64
    - python: "3.3"
      env: BITS=64
    - python: "3.4"
      env: BITS=64

before_install:
  - sudo add-apt-repository ppa:ubuntu-wine/ppa -y
  - sudo apt-get update
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - sudo apt-get install -y --force-yes wine
  - pip install coveralls
  - sh scripts/setup_tests_wine.sh

script:
  - sh scripts/run_tests_wine.sh

after_success:
  - pip install codecov
  - codecov
