language: python

python:
  - "2.7"

before_install:
  - sudo add-apt-repository ppa:ubuntu-wine/ppa
  - sudo apt-get update
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - sudo apt-get install wine
  - sh scripts/setup_tests_wine.sh

script:
  - echo "Ok"
    #  - sh scripts/run_tests_wine.sh
