build: false
shallow_clone: true
skip_branch_with_pr: true

environment:

  matrix:
    - python: "C:/Python27-x64"
    - python: "C:/Python27"
    - python: "C:/Python35-x64"
    - python: "C:/Python35"
    - python: "C:/Python36-x64"
    - python: "C:/Python36"


cache:
  - C:\Users\appveyor\AppData\Local\pip\Cache


init:
  - ps: $Env:path = $Env:python + ";" + $Env:python + "\scripts;" + $Env:path

install:
  - ps: pip install --upgrade pip wheel
  - ps: pip --version
  - ps: pip install coverage
  - ps: pip --only-binary pypiwin32 pypiwin32
  - ps: pip install -e .
test_script:
  - cmd: ./scripts/appveyor-test.cmd
on_success:
  - cd testrun
  - pip install codecov
  - codecov
