build: false
shallow_clone: true
environment:

  global:
    distutils_use_sdk: 1

  matrix:
    - python: "C:/Python27-x64"
      sdkver: "v7.0"
      pywin32: "http://sourceforge.net/projects/pywin32/files/pywin32/Build%20219/pywin32-219.win-amd64-py2.7.exe/download"

    - python: "C:/Python33-x64"
      sdkver: "v7.1"
      pywin32: "http://sourceforge.net/projects/pywin32/files/pywin32/Build%20219/pywin32-219.win-amd64-py3.2.exe/download"
    - python: "C:/Python34-x64"
      sdkver: "v7.1"
      pywin32: "http://sourceforge.net/projects/pywin32/files/pywin32/Build%20219/pywin32-219.win-amd64-py3.4.exe/download"

cache:
  - c:\egg_cache

init:
  - ps: $Env:sdkbin = "C:\Program Files\Microsoft SDKs\Windows\" + $Env:sdkver + "\Bin"
  - ps: $Env:sdkverpath = "C:/Program Files/Microsoft SDKs/Windows/" + $Env:sdkver + "/Setup/WindowsSdkVer.exe"
  - ps: $Env:path = $Env:python + ";" + $Env:python + "\scripts;" + $Env:sdkbin + ";" + $Env:path
install:
  - ps: if ((Test-Path "c:/egg_cache") -eq 0) { mkdir c:/egg_cache }
  - ps: (new-object net.webclient).DownloadFile('https://raw.github.com/pypa/pip/master/contrib/get-pip.py', 'c:/get-pip.py')
  - ps: python c:/get-pip.py
  - ps: pip --version
  - ps: (new-object net.webclient).DownloadFile($Env:pywin32, 'pywin32.exe')
  - cmd /v:on /e:on /c ".\scripts\appveyor-install.cmd"
test_script:
  - ps: ls